export enum DockStatus {
  OPERATIONAL = 'OPERATIONAL',
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  MAINTENANCE_REQUESTED = 'MAINTENANCE_REQUESTED',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  DECOMMISSIONED = 'DECOMMISSIONED',
}
