export enum BikeStatus {
  NEW = 'NEW',
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  MAINTENACE_REQUESTED = 'MAINTENANCE_REQUESTED',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
}
